name: Main
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    
jobs:
  publish-image:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/publish.yml
    secrets: inherit