name: 'Publish Image'

permissions:
  id-token: write
  contents: write
  actions: write
  pull-requests: write
  packages: read

on:
  workflow_call:
    inputs:
      settings-file:
        description: 'Path to the settings file'
        required: false
        type: string
        default: 'settings.yml'
      docker-file-path:
        description: 'Path to the Dockerfile'
        required: false
        type: string
        default: '.'
      runs-on:
        description: 'Runner label to use'
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  build-image:
    name: Build Image
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - name: Run YAML to Github Output Action
        id: settings-parser
        uses: christian-ci/action-yaml-github-output@v2
        with:
          file_path: './${{ inputs.settings-file }}'
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker Image
        working-directory: '${{ inputs.docker-file-path }}'
        run: |
          docker build -t ${{ steps.settings-parser.outputs.registry}}/${{ steps.settings-parser.outputs.repository}}:${GITHUB_SHA:0:7} .

      - name: Push Docker Image
        run: |
          docker push ${{ steps.settings-parser.outputs.registry}}/${{ steps.settings-parser.outputs.repository}}:${GITHUB_SHA:0:7}
        working-directory: '${{ inputs.docker-file-path }}'